---
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Allow State classes of StatefulWidgets to be private.
    library_private_types_in_public_api: ignore

    # Desirable, but experimental.
    use_build_context_synchronously: ignore

linter:
  rules:
    - directives_ordering
    - flutter_style_todos
