#!/bin/sh
# To use add to `.git/hooks/`
# Should be named `pre-commit`
# Make executable with `chmod +x`

# make sure code is correctly formatted
flutter format .

# run code style checks
flutter analyze
if [ $? -ne 0 ]; then
  exit 1
fi

# getting to this point symbolises success
exit 0
