---
name: Coverage Report

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Print the Flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Ensure code coverage checks correct files
        run: |
          chmod +x bin/prep_files_for_code_coverage_check.sh
          sudo ./bin/prep_files_for_code_coverage_check.sh tap_canvas
      - name: Run the tests (with coverage)
        run: flutter test --coverage
      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: "${{ secrets.CODECOV_TOKEN }}"
